---
title: |
  | Lab 1.
  | Basic R Programming
author: |
  | Suhwan Bong
  | Department of Statistics
  | Seoul National Univ.
date: "2022-09-05"
output: html_document
---

## 1. Introduction

In this chapter, we will study basic R commands.

### Scalars

```{r}
x <- 3
y = (1+2)^3
"Hello" -> z

x;y;z;
```

### Vectors

```{r}
a <- c(1,3,5,7)
b <- c(2,4,6,8)

a+b
a*b

# Generate vectors with seq() function.
seq(from=1, to=10, by=1)
seq(from=1, to=15, length=5)
seq(from=1, by=2, length=5)

# Generate vectors with rep() function.
rep(3,5)
rep(c(1,2,3),2)
3:10
10:3
```

### Matrices

```{r}
A <- matrix(c(1,3,5,7,9,11), ncol=2)
B <- matrix(c(1,3,5,7,9,11), ncol=2, byrow=T)

A;B;

C <- cbind(a,b)
D <- rbind(a,b)

C;D;
```

### Functions

```{r}
x <- 2.53
y <- 3.45
z <- 8

abs(x)
sqrt(z)
round(x, digits = 1)
round(y)

log(z)
log(z, base=10)

choose(5,3)
factorial(5)

paste("z=",z)
paste0("z=",z)
```

### Operators

```{r}
a <- 5
b <- 2

a+b
a-b
a*b
a/b

a^b
a%/%b
a%%b

(a%%b)==1
(a%/%b)!=2
```

### Other statements

```{r}
# For Loop
for (i in 1:5){
  print(i)
}
for (j in 5:1){
  print(j)
}

# If-Else Statement
if (3<5) {print("yes")}

if (3<5){
  print("yes")
}else{
  print("no")
}

for (i in 1:5){
  if(i%%2==0){
    print(i)
  }
}
```

## 2. Handling Data

In this chapter, we will study ways to handle data.

### Data Frame

```{r}
id <- c(1,2,3,4,5)
gender <- c("F","M","M","F","F")
math <- c(66,64,48,46,78)
eng <- c(70,68,46,48,81)

score <- data.frame(id,gender,math,eng)
score
```

### Read and write csv files

```{r}
write.csv(score,file="score.csv")
data <- read.csv("score.csv")
data

write.csv(score,file="score2.csv", row.names = F)
data2 <- read.csv("score2.csv")
data2
```

### Histogram
```{r}
hist(score$eng)
hist(score$eng, freq=F)
hist(score$eng, breaks=5)
```

### Stem and Leaf Plot
```{r}
stem(score$eng)
```

### Box plot
```{r}
boxplot(score$eng)
```

### Summary of data
```{r}
table(score$gender)
fivenum(score$math)
summary(score$math)

plot(score$math,score$eng)
cor(score$math,score$eng)
```

## 3. Distributions

### Normal distribution
```{r}
# density function
dnorm(0, mean=0, sd=1)
x <- seq(from=-3, to=3, by=0.1)
fx <- dnorm(x, mean=0, sd=1)
plot(x, fx, type = "l")

# distribution function
pnorm(0, mean=0, sd=1) # Pr(X<=0)

# quantile function
qnorm(p=0.025, mean=0, sd=1) # Pr(X<=x)=p

# random deviate
rnorm(5, mean=0, sd=1)
```

### Binomial distribution
```{r}
dbinom(2, size=4, prob=0.5)
pbinom(2, size=4, prob=0.5)
```